# Generated by Django 3.2.7 on 2021-09-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_text', models.TextField()),
                ('citation_text_quality', models.IntegerField()),
                ('citation_intent_quality', models.BooleanField()),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name='create time')),
            ],
        ),
    ]
